### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by bookchin** [kadtools/kad-onion#4]
```
{"name":"ff3401014c04e13f2e19554420ffae817fb0c4e4","hostname":"server019","pid":2505,"level":30,"msg":"performing routine service availability check","time":"2017-07-26T16:31:30.660Z","v":0}
{"name":"ff3401014c04e13f2e19554420ffae817fb0c4e4","hostname":"server019","pid":2505,"level":30,"msg":"sending PING (2bb0b561-3dfd-4c09-9849-e667fc529bdd) to ff3401014c04e13f2e19554420ffae817fb0c4e4 (https://undefined:443)","time":"2017-07-26T16:31:30.661Z","v":0}
{"name":"ff3401014c04e13f2e19554420ffae817fb0c4e4","hostname":"server019","pid":2505,"level":40,"msg":"connect econnrefused 127.0.0.1:443","time":"2017-07-26T16:31:30.675Z","v":0}
{"name":"ff3401014c04e13f2e19554420ffae817fb0c4e4","hostname":"server019","pid":2505,"level":40,"msg":"availability check failed, re-establishing","time":"2017-07-26T16:32:01.170Z","v":0}
/root/orc/node_modules/kad-onion/index.js:187
            self.node.contact.hostname.split('.')[0],
                                      ^

TypeError: Cannot read property 'split' of undefined
    at self._checkIfReachable.isReachable (/root/orc/node_modules/kad-onion/index.js:187:39)
    at Object.node.ping [as handler] (/root/orc/node_modules/kad-onion/index.js:217:7)
    at Node._timeout (/root/orc/node_modules/kad/lib/node-abstract.js:171:13)
    at Timeout.setInterval [as _onTimeout] (/root/orc/node_modules/kad/lib/node-abstract.js:99:28)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by bookchin** [comment]
Closed by https://github.com/kadtools/kad-onion/commit/d6b1de39dae6d0820cabaf664933b1a132921a52
